name: Get changed workspaces
description: A github action that gets changed workspaces
author: Aleksandras Sukelovic <alex.shukel@gmail.com>
inputs:
    base-ref:
        description: |
            Git base reference (branch name or a commit hash). The change list will be compared to the base if
            push event occurs. Will default to the last commit of the current branch
        required: false
        default: ${{ github.ref }}
    workspaces:
        description: Paths where to get changed workspaces
        required: false
    package-path:
        description: Path to root package.json directory
        required: false
        default: "."
outputs:
    changed_workspaces:
        description: Array of changed workspaces

runs:
    using: node16
    main: dist/index.js
